"""empty message

Revision ID: 19a6b78d087b
Revises: 59ecabd263ac
Create Date: 2015-06-19 16:50:40.546304

"""

# revision identifiers, used by Alembic.
revision = '19a6b78d087b'
down_revision = '59ecabd263ac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
