"""empty message

Revision ID: 34a34ed69afc
Revises: 4f90fbd82394
Create Date: 2015-06-18 17:38:29.327608

"""

# revision identifiers, used by Alembic.
revision = '34a34ed69afc'
down_revision = '4f90fbd82394'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
