"""empty message

Revision ID: 40a3e2a59062
Revises: 34a34ed69afc
Create Date: 2015-06-18 17:39:10.126493

"""

# revision identifiers, used by Alembic.
revision = '40a3e2a59062'
down_revision = '34a34ed69afc'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('note', 'last_updated',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.add_column('user', sa.Column('create_time', sa.DATETIME(), nullable=True))
    op.drop_column('user', 'timestamp')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('timestamp', mysql.DATETIME(), nullable=False))
    op.drop_column('user', 'create_time')
    op.alter_column('note', 'last_updated',
               existing_type=mysql.DATETIME(),
               nullable=False)
    ### end Alembic commands ###
