"""empty message

Revision ID: 4f90fbd82394
Revises: 140facbf6deb
Create Date: 2015-06-18 17:37:40.502422

"""

# revision identifiers, used by Alembic.
revision = '4f90fbd82394'
down_revision = '140facbf6deb'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.drop_column('user', 'isAdmin')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isAdmin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('user', 'is_admin')
    ### end Alembic commands ###
