"""empty message

Revision ID: 59ecabd263ac
Revises: 90b7616535f
Create Date: 2015-06-18 17:51:30.186921

"""

# revision identifiers, used by Alembic.
revision = '59ecabd263ac'
down_revision = '90b7616535f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_name', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_user_user_name'), 'user', ['user_name'], unique=True)
    op.drop_column('user', 'name')
    op.drop_column('user', 'email')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('user', sa.Column('name', mysql.VARCHAR(length=100), nullable=False))
    op.drop_index(op.f('ix_user_user_name'), table_name='user')
    op.drop_column('user', 'user_name')
    ### end Alembic commands ###
