"""empty message

Revision ID: 90b7616535f
Revises: 40a3e2a59062
Create Date: 2015-06-18 17:43:25.641882

"""

# revision identifiers, used by Alembic.
revision = '90b7616535f'
down_revision = '40a3e2a59062'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('user', sa.Column('name', sa.String(length=100)))
    # op.create_index(op.f('ix_user_name'), 'user', ['name'])
    # op.drop_index('ix_user_email', table_name='user')
    # op.drop_column('user', 'email')
    ### end Alembic commands ###
    pass


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', mysql.VARCHAR(length=100), nullable=False))
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_column('user', 'name')
    ### end Alembic commands ###
